### ISSUE TITLE
Jhipster 4 and Angular 2

### ISSUE THREAD

**Issue by devozs** [m2asolutions/JWebShop#1]
Hi,

Thank you for that example project.
Do you have such cart and shopping example for jhipster 4 and / or angular 2?

If not, any idea if ngCart will work with Angular 2?

Thanks.

**Comment by anunnakian** [comment]
I'm sorry, I can't upgrade this example project to angular 2 in this moment. For ngCart you can check the repo [here](https://github.com/snapjay/ngCart)

**Comment by devozs** [comment]
Thanks... I've posted a query on ngCart thread to check if and when it will
be supported.

Thanks again.
